### ISSUE TITLE
Sandbox variables Scratchbook

### ISSUE THREAD

**Issue by OmarEdraak** [Edraak/edx-configuration#7]
@devalih I've removed a ton of variable from the sandbox vars file. Keeping it here for reference.

```yaml


# certs_version: master
# demo_version
# INSIGHTS_VERSION
# ANALYTICS_API_VERSION
# ECOMMERCE_VERSION
# ECOMMERCE_WORKER_VERSION
# DISCOVERY_VERSION
# THEMES_VERSION





#AWS_S3_LOGS: true
#
#AWS_S3_LOGS_NOTIFY_EMAIL: ""
#AWS_S3_LOGS_FROM_EMAIL: ""
#
#aws_region: "us-west-2"

#s3_bucket: '-'

# Common role

#COMMON_ENABLE_BASIC_AUTH: True

#COMMON_AWS_SYNC: True
#COMMON_AWS_SYNC_BUCKET: "-"
#
#COMMON_ENABLE_NEWRELIC_APP: True


#EDXAPP_MYSQL_HOST: '-'
#EDXAPP_EMAIL_HOST:

#EDXAPP_MEMCACHE:
#   - '-'

#EDXAPP_COMMENTS_SERVICE_URL:  '-'

#EDXAPP_GOOGLE_ANALYTICS_ACCOUNT: "-"

#EDXAPP_CELERY_USER: '-'
#EDXAPP_CELERY_BROKER_VHOST: "-"

#EDXAPP_YOUTUBE_API_KEY: "-"


#### Marketing URLs ####

#EDXAPP_ENABLE_MKTG_SITE: true

#EDXAPP_MKTG_URLS:
#  ROOT: "https://{{ MARKETING_DOMAIN }}/"
#  HOME: ""
#  ABOUT: "about-us"
#  HOW_IT_WORKS: "help/how-it-works"
#  ENROLL_SUCCESS: "success/{course_id}"
#  COURSES: "courses"
#  COURSE_INFO: "course/{course_id}"
#  TEACH: "teach"
#  PRIVACY: "privacy-policy"
#  TOS: "terms-of-service"
#  CONTACT: "contact-us"
#  FAQ: "help/faq/"
#  HONOR: "honor"
#  PRESS: "press"
#  BLOG: "blog"
#  DONATE: "donate"
#  WHAT_IS_VERIFIED_CERT: "verified-certificate"
#  SPECIALIZATION_INFO: "specialization/{slug}"

#EDXAPP_PROGS_URLS:
#  ROOT: "https://{{ PROGS_DOMAIN }}/"
#  PROG_API: "api/programs/{program_slug}/?type=spc"
#  PROG_LMS: "learn/program/{program_slug}"
#  DASHBOARD: "learn"

#### Third Party Auth ####

#EDXAPP_ENABLE_THIRD_PARTY_AUTH: true

#EDXAPP_THIRD_PARTY_AUTH:
#  Google:
#    SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "{{ VAULT_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }}"
#    SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "{{ VAULT_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }}"
#  Facebook:
#    SOCIAL_AUTH_FACEBOOK_KEY: "{{ VAULT_SOCIAL_AUTH_FACEBOOK_KEY }}"
#    SOCIAL_AUTH_FACEBOOK_SECRET: "{{ VAULT_SOCIAL_AUTH_FACEBOOK_SECRET }}"

#EDXAPP_OAUTH_ENFORCE_SECURE: False
#EDXAPP_OAUTH_ENFORCE_CLIENT_SECURE: False
#EDXAPP_ANALYTICS_DASHBOARD_URL: "-"

EDXAPP_ENV_EXTRA:
  AUTH_REDIRECT_ALLOW_ANY: False
  AUTH_REDIRECT_ORIGINS_WHITELIST: []

EDXAPP_AUTH_EXTRA:
  FORUS_AUTH_SECRET_KEY: "{{ VAULT_FORUS_AUTH_SECRET_KEY }}"

#EDXAPP_CELERY_BROKER_HOSTNAME: "-"

#EDXAPP_RABBIT_HOSTNAME: '-'


#EDXAPP_GRADE_STORAGE_TYPE: 's3'
#EDXAPP_GRADE_BUCKET: '-'
#EDXAPP_GRADE_ROOT_PATH: 'edraak'

#EDXAPP_EDX_API_KEY: "-"


# CSRF settings
#EDXAPP_CSRF_TRUSTED_ORIGINS:
#  - "{{ EDXAPP_LMS_BASE }}"
#  - "{{ MARKETING_DOMAIN }}"
#  - "{{ PROGS_DOMAIN }}"
#  - "qrta.{{ EDXAPP_DOMAIN }}"
#  - "ju.{{ EDXAPP_DOMAIN }}"
#  - "hu.{{ EDXAPP_DOMAIN }}"
#  - "le.{{ EDXAPP_DOMAIN }}"
#EDXAPP_SAFE_REDIRECT_HOSTS:
#  - "{{ EDXAPP_LMS_BASE }}"
#  - "{{ MARKETING_DOMAIN }}"
#  - "{{ PROGS_DOMAIN }}"
#  - "qrta.{{ EDXAPP_DOMAIN }}"
#  - "ju.{{ EDXAPP_DOMAIN }}"
#  - "hu.{{ EDXAPP_DOMAIN }}"
#  - "le.{{ EDXAPP_DOMAIN }}"

#EDXAPP_AWS_STORAGE_BUCKET_NAME: '-'

#EDXAPP_MEDIA_URL:  "https://{{ EDXAPP_AWS_STORAGE_BUCKET_NAME }}.{{ EDXAPP_DOMAIN }}/media"

#EDXAPP_VIDEO_UPLOAD_PIPELINE:
#  BUCKET: '-'
#  ROOT_PATH: '-'
#  CONCURRENT_UPLOAD_LIMIT: 20
#  COURSE_VIDEO_UPLOAD_TOKEN: '-'

#EDXAPP_CORS_ORIGIN_WHITELIST:
#  - "{{ PROGS_DOMAIN }}"
#  - "{{ MARKETING_DOMAIN }}"


######

edxapp_use_custom_theme: false
#edxapp_theme_name: "edraak-2015"
#edxapp_theme_source_repo: '-'
#edxapp_theme_version: 'master'

#EDXAPP_SESSION_COOKIE_SECURE: true
#EDXAPP_CSRF_COOKIE_SECURE: true


#FORUM_MONGO_HOSTS: # edraak_cs_comments_service-deployment
#  - "-"

#FORUM_MONGO_PORT: "-"
#FORUM_MONGO_DATABASE: "-"
#FORUM_SINATRA_ENV: "production"
#FORUM_RACK_ENV: "production"
#FORUM_ELASTICSEARCH_HOST: "-"

#MARKETING_ENFORCE_HTTPS: True
#EDXAPP_ENFORCE_HTTPS: True
#NGINX_REDIRECT_TO_HTTPS: True


# NEWRELIC

#NEWRELIC_LICENSE_KEY: "-"
# Mongodb

#MMSAPIKEY: "-"

# zendesk

#EDXAPP_ZENDESK_USER: "-"
#EDXAPP_ZENDESK_URL: "https://edraak.zendesk.com/"
#EDXAPP_ZENDESK_API_KEY: "-"

#EDXAPP_FORUS_BASE_URL: "http://forus.jo"

```
